import Head from 'next/head'
import  RichEditor   from "../pages/RichEditor"

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Typedream Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RichEditor />
      </main>
    </div>
  )
}

